Repository CalenDev/calendev, pull requests merged in 2022-11, with the labels that each got.

#15 DEV-12 프론트엔드 기본 환경 세팅
  Client/.eslintrc.json
  Client/.gitignore
  Client/package-lock.json
  Client/package.json
  Client/public/favicon.ico
  Client/public/index.html
  Client/src/styles/themes.js
Labels: environment, front-end, layout

#16 DEV-35 공통 메세지 함수 구현
  Client/src/utils/commonMsgText.js
Labels: sub-task, front-end

#17 DEV-14 CustomTextField 공통 컴포넌트 구현
  Client/src/components/CustomTextField/index.jsx
  Client/src/components/index.js
Labels: feature, front-end, layout

#18 Dev 52 implement load balancing
  server/.gitignore
  server/backend/src/.eslintrc.json
  server/backend/src/.gitignore
  server/backend/src/.prettierrc.json
  server/backend/src/app.js
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/controllers/errorController.js
  server/backend/src/domain/user/controllers/index.js
  server/backend/src/domain/user/controllers/userController.js
  server/backend/src/domain/user/dto/joinDto.js
  server/backend/src/domain/user/dto/loginDto.js
  server/backend/src/domain/user/dto/userDto.js
  server/backend/src/domain/user/models/user.js
  server/backend/src/domain/user/routes/authRoutes.js
  server/backend/src/domain/user/routes/userRoutes.js
  server/backend/src/domain/user/service/userJoinService.js
  server/backend/src/domain/user/service/userLogInService.js
  server/backend/src/domain/user/service/userUpdateService.js
  server/backend/src/domain/user/utils/dttmBuilder.js
  server/backend/src/global/config/knexConfig.js
  server/backend/src/global/config/mongoConfig.js
  server/backend/src/global/config/mysql2Config.js
  server/backend/src/global/security/jwt.js
  server/backend/src/global/utils/appError.js
  server/backend/src/global/utils/catchAsync.js
  server/backend/src/global/utils/encrypt.js
  server/backend/src/global/utils/objectMapper.js
  server/backend/src/global/utils/passwordEncoder.js
  server/backend/src/global/utils/requestReg.js
  server/backend/src/global/utils/requestValidator.js
  server/backend/src/package-lock.json
  server/backend/src/package.json
  server/middleware/src/.gitignore
  server/middleware/src/api/index.js
  server/middleware/src/app.js
  server/middleware/src/package-lock.json
  server/middleware/src/package.json
Labels: feature, back-end

#19 dev-51 header component
  Client/.eslintrc.json
  Client/.gitignore
  Client/.prettierrc.json
  Client/README.md
  Client/src/App.jsx
  Client/src/api/index.js
  Client/src/assets/images/CalendevLogo.png
  Client/src/assets/index.js
  Client/src/components/CustomTextField/index.jsx
  Client/src/components/Header/index.jsx
  Client/src/components/index.js
  Client/src/config/index.js
  Client/src/container/index.js
  Client/src/index.jsx
  Client/src/modules/index.js
  Client/src/pages/Home/Home.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/pages/SignUp/SignUp.jsx
  Client/src/styles/index.js
  Client/src/utils/index.js
Labels: feature, front-end

#20 DEV-40 CommonPaper 공통 컴포넌트 구현
  Client/src/components/CommonPaper/index.jsx
  Client/src/components/index.js
Labels: feature, front-end

#21 DEV-39 validate the login
  Client/package-lock.json
  Client/package.json
  Client/src/api/auth.js
  Client/src/api/index.js
  Client/src/index.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/utils/commonMsgText.js
  Client/src/utils/index.js
  Client/src/utils/validationCheck.js
Labels: feature, front-end
