Repository CalenDev/calendev, pull requests merged in 2023-01, with the labels that each got.

#26 Ekgns33/enhance/create error enums and post enum (latest version)
  server/backend/src/app.js
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/controllers/errorController.js
  server/backend/src/domain/user/controllers/userController.js
  server/backend/src/domain/user/service/userEmailService.js
  server/backend/src/domain/user/service/userJoinService.js
  server/backend/src/domain/user/service/userLogInService.js
  server/backend/src/domain/user/service/userUpdateService.js
  server/backend/src/global/common/Enum/category.js
  server/backend/src/global/common/Enum/companyTag.js
  server/backend/src/global/common/Enum/eventTag.js
  server/backend/src/global/common/Enum/skillFieldTag.js
  server/backend/src/global/common/Enum/skillTag.js
  server/backend/src/global/common/errorCode.js
  server/backend/src/global/security/refresh.js
Labels: enhancement, back-end

#28 DEV-62 modify header responsive style
  Client/.eslintrc.json
  Client/src/App.jsx
  Client/src/components/Header/index.jsx
Labels: feature, front-end

#27 Ekgns33/feature/dev 54 implement user login service
  server/backend/src/app.js
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/controllers/errorController.js
  server/backend/src/domain/user/controllers/index.js
  server/backend/src/domain/user/controllers/userController.js
  server/backend/src/domain/user/dto/updateDto.js
  server/backend/src/domain/user/dto/userDto.js
  server/backend/src/domain/user/models/user.js
  server/backend/src/domain/user/routes/authRoutes.js
  server/backend/src/domain/user/routes/userRoutes.js
  server/backend/src/domain/user/service/userEmailService.js
  server/backend/src/domain/user/service/userJoinService.js
  server/backend/src/domain/user/service/userLogInService.js
  server/backend/src/domain/user/service/userUpdateService.js
  server/backend/src/domain/user/utils/dttmBuilder.js
  server/backend/src/global/common/Enum/category.js
  server/backend/src/global/common/Enum/companyTag.js
  server/backend/src/global/common/Enum/eventTag.js
  server/backend/src/global/common/Enum/skillFieldTag.js
  server/backend/src/global/common/Enum/skillTag.js
  server/backend/src/global/common/errorCode.js
  server/backend/src/global/config/knexConfig.js
  server/backend/src/global/config/mongoConfig.js
  server/backend/src/global/config/redisCofig.js
  server/backend/src/global/security/jwt.js
  server/backend/src/global/security/refresh.js
  server/backend/src/global/utils/appError.js
  server/backend/src/global/utils/encrypt.js
  server/backend/src/global/utils/requestReg.js
  server/backend/src/global/utils/requestValidator.js
  server/backend/src/global/utils/sendEmail.js
  server/backend/src/package-lock.json
  server/backend/src/package.json
Labels: feature, back-end

#29 DEV-36 send a password reset link
  Client/src/App.jsx
  Client/src/api/auth.js
  Client/src/api/index.js
  Client/src/components/CommonPaper/index.jsx
  Client/src/pages/FindPw/FindPw.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/utils/commonMsgText.js
Labels: feature, front-end

#30 DEV-37 work password reset link
  Client/package-lock.json
  Client/package.json
  Client/src/App.jsx
  Client/src/api/auth.js
  Client/src/api/index.js
  Client/src/assets/index.js
  Client/src/config/config.js
  Client/src/config/themes.js
  Client/src/container/index.js
  Client/src/features/GlobalModal/GlobalModalSlice.js
  Client/src/features/GlobalModal/index.jsx
  Client/src/index.jsx
  Client/src/modules/index.js
  Client/src/pages/Error/Error.jsx
  Client/src/pages/ResetPw/ResetPw.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/store/index.js
  Client/src/store/rootReducer.js
  Client/src/utils/commonModalText.js
  Client/src/utils/index.js
  Client/src/utils/url.js
Labels: feature, front-end

#32 feat: DEV-64 공통 Flex 컴포넌트 CommonStack 생성
  Client/src/components/CommonStack/index.jsx
  Client/src/components/index.js
Labels: sub-task, front-end

#34 Ekgns33/enhance/fix jwtservice and create user role cd enum
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/controllers/userController.js
  server/backend/src/domain/user/models/user.js
  server/backend/src/domain/user/service/userJoinService.js
  server/backend/src/domain/user/service/userLogInService.js
  server/backend/src/global/common/Enum/category.js
  server/backend/src/global/common/Enum/companyTag.js
  server/backend/src/global/common/Enum/eventTag.js
  server/backend/src/global/common/Enum/skillFieldTag.js
  server/backend/src/global/common/Enum/skillTag.js
  server/backend/src/global/common/Enum/userRoleCd.js
  server/backend/src/global/common/errorCode.js
  server/backend/src/global/security/jwt.js
  server/backend/src/global/security/refresh.js
Labels: enhancement

#35 Feat: dayeon-alert/feature/DEV-11-General-Register-Page
  Client/src/api/index.js
  Client/src/api/user.js
  Client/src/pages/SignUp/SignUp.jsx
Labels: feature, front-end, layout

#37 feat: create CommonSelectBox component (DEV-66)
  Client/src/components/CommonSelectBox/index.jsx
  Client/src/components/index.js
Labels: feature, front-end

#38 feat: create CommonGroupChips Component (DEV-67)
  Client/src/components/CommonGroupChips/index.jsx
  Client/src/components/index.js
Labels: feature, front-end

#39 chore: add config files (DEV-68)
  Client/src/config/eventTag.js
  Client/src/config/skillTag.js
  Client/src/config/techFieldTag.js
Labels: sub-task, front-end

#36 DEV-60 auth system throught jwt
  Client/package-lock.json
  Client/package.json
  Client/src/.gitattributes
  Client/src/App.jsx
  Client/src/api/auth.js
  Client/src/api/instance.js
  Client/src/api/user.js
  Client/src/components/Header/index.jsx
  Client/src/components/index.js
  Client/src/features/User/UserSlice.js
  Client/src/index.jsx
  Client/src/pages/FindPw/FindPw.jsx
  Client/src/pages/ResetPw/ResetPw.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/pages/SignUp/SignUp.jsx
  Client/src/store/index.js
  Client/src/store/persistedReducer.js
  Client/src/store/rootReducer.js
  Client/src/styles/themes.js
  Client/src/utils/commonApiRes.js
  Client/src/utils/commonModalText.js
Labels: feature, front-end

#40 fix: edit email input max length to 20 (DEV-69)
  Client/src/pages/FindPw/FindPw.jsx
  Client/src/pages/SignUp/SignUp.jsx
Labels: bug, front-end

#42 Ekgns33/feature/dev 65 implement user search system
  server/backend/src/domain/post/controllers/postControllers.js
  server/backend/src/domain/post/models/post.js
  server/backend/src/domain/post/routes/postRoutes.js
  server/backend/src/domain/post/searchSystem/PostTextTokenizer.js
  server/backend/src/domain/post/searchSystem/SearchQuery.js
  server/backend/src/domain/post/searchSystem/postIndex.js
  server/backend/src/domain/post/service/postService.js
  server/backend/src/domain/post/service/searchService.js
  server/backend/src/global/common/errorCode.js
  server/backend/src/global/utils/requestValidator.js
  server/backend/src/package-lock.json
  server/backend/src/package.json
Labels: feature, back-end

#43 Ekgns33/feature/dev 57 implement post crud system
  server/backend/src/app.js
  server/backend/src/domain/post/controllers/postControllers.js
  server/backend/src/domain/post/dto/postDto.js
  server/backend/src/domain/post/models/mongoErrorHandler.js
  server/backend/src/domain/post/models/post.js
  server/backend/src/domain/post/routes/postRoutes.js
  server/backend/src/domain/post/searchSystem/PostTextTokenizer.js
  server/backend/src/domain/post/searchSystem/SearchQuery.js
  server/backend/src/domain/post/searchSystem/postIndex.js
  server/backend/src/domain/post/service/postService.js
  server/backend/src/domain/post/service/searchService.js
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/controllers/errorController.js
  server/backend/src/global/common/errorCode.js
  server/backend/src/global/security/jwt.js
  server/backend/src/global/utils/objectMapper.js
  server/backend/src/global/utils/requestValidator.js
  server/backend/src/package-lock.json
  server/backend/src/package.json
Labels: feature, back-end

#44 Suhwan2004/feature/dev 25 search events by conditions
  Client/package-lock.json
  Client/src/api/auth.js
  Client/src/api/index.js
  Client/src/api/post.js
  Client/src/components/CommonDttmPicker/index.jsx
  Client/src/components/CommonFilter/index.jsx
  Client/src/components/CommonSearchBar/index.jsx
  Client/src/components/CommonSelect/index.jsx
  Client/src/components/CommonSelectBox/index.jsx
  Client/src/components/index.js
  Client/src/utils/change.js
  Client/src/utils/validationCheck.js
Labels: feature, front-end

#45 Ekgns33/fix/user management service
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/service/userUpdateService.js
Labels: bug

#46 Ekgns33/feature/dev 71 북마크 기능추가
  server/backend/src/domain/post/controllers/postControllers.js
  server/backend/src/domain/post/models/bookmark.js
  server/backend/src/domain/post/routes/postRoutes.js
  server/backend/src/domain/post/service/bookmarkService.js
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/dto/loginDto.js
  server/backend/src/domain/user/service/userLogInService.js
Labels: feature, back-end

#47 DEV-58 view event by calendar
  Client/package-lock.json
  Client/package.json
  Client/src/App.jsx
  Client/src/api/index.js
  Client/src/api/instance.js
  Client/src/api/post.js
  Client/src/components/CommonFilter/index.jsx
  Client/src/features/Bookmark/BookmarkSlice.js
  Client/src/pages/Error/Error.jsx
  Client/src/pages/FindPw/FindPw.jsx
  Client/src/pages/Post/PostCalendar/PostCalendar.jsx
  Client/src/pages/ResetPw/ResetPw.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/pages/SignUp/SignUp.jsx
  Client/src/store/persistedReducer.js
  Client/src/utils/index.js
Labels: feature, front-end

#51 Suhwan2004/feature/dev 73 edit calender page
  Client/src/features/Bookmark/BookmarkSlice.js
  Client/src/pages/Post/PostCalendar/PostCalendar.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/store/persistedReducer.js
Labels: feature, front-end

#50 Ekgns33/feature/dev 72 implement post view update system
  server/backend/src/app.js
  server/backend/src/domain/post/controllers/postControllers.js
  server/backend/src/domain/post/dto/postDto.js
  server/backend/src/domain/post/models/post.js
  server/backend/src/domain/post/service/postService.js
Labels: back-end

#52 Ekgns33/fix/dev 75 fix login error with bookmark
  server/backend/src/domain/post/models/bookmark.js
  server/backend/src/domain/post/routes/postRoutes.js
  server/backend/src/domain/post/service/bookmarkService.js
  server/backend/src/domain/post/service/postService.js
  server/backend/src/domain/user/controllers/authController.js
  server/backend/src/domain/user/service/userJoinService.js
Labels: bug, back-end

#53 feat: create write post page (DEV-21)
  Client/src/App.jsx
  Client/src/api/index.js
  Client/src/api/post.js
  Client/src/pages/WritePost/WritePost.jsx
  Client/src/utils/commonMsgText.js
  Client/src/utils/formatter.js
  Client/src/utils/index.js
  Client/src/utils/validationCheck.js
Labels: feature, front-end

#54 Suhwan2004/feature/dev 76 page routing user role cd
  Client/src/App.jsx
  Client/src/components/PrivateRoute/index.jsx
  Client/src/pages/SignIn/SignIn.jsx
  Client/src/pages/WritePost/WritePost.jsx
  Client/src/utils/commonApiRes.js
  Client/src/utils/commonModalText.js
  server/backend/src/global/config/knexConfig.js
Labels: feature, front-end

#55 feat: view post detail page (DEV-26)
  Client/src/App.jsx
  Client/src/api/index.js
  Client/src/api/post.js
  Client/src/pages/Post/PostCalendar/PostCalendar.jsx
  Client/src/pages/PostDetail/PostDetail.jsx
Labels: feature, front-end

#57 DEV-77 separate calendar by login
  Client/src/pages/Post/PostCalendar/PostCalendar.jsx
  Client/src/utils/commonEventGetter.js
  Client/src/utils/index.js
Labels: feature, front-end

#58 DEV-78 remove: 백엔드 설계 변경에 따른 디렉토리 삭제
  server/middleware/src/.gitignore
  server/middleware/src/api/index.js
  server/middleware/src/app.js
  server/middleware/src/package-lock.json
  server/middleware/src/package.json
Labels: feature, back-end

#59 DEV-79 fix: Post.js postPlace required 삭제
  server/backend/src/domain/post/models/post.js
Labels: bug, back-end

#61 feat: develop delete post function (DEV-81)
  Client/src/api/index.js
  Client/src/api/post.js
  Client/src/pages/PostDetail/PostDetail.jsx
Labels: feature, front-end

#62 feat: implement phone num validate (DEV-74)
  Client/src/pages/WritePost/WritePost.jsx
  Client/src/utils/commonMsgText.js
Labels: feature, front-end

#63 DEV-82 fix: 레디스 host 주소 설정 변경
  server/backend/src/global/config/redisCofig.js
Labels: bug, back-end
